/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MyMoneyRouteImport } from './routes/my-money'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FriendsIndexRouteImport } from './routes/friends.index'
import { Route as FriendsFriendIdRouteImport } from './routes/friends.$friendId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MyMoneyRoute = MyMoneyRouteImport.update({
  id: '/my-money',
  path: '/my-money',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/friends/$friendId',
  path: '/friends/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/my-money': typeof MyMoneyRoute
  '/settings': typeof SettingsRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/friends/': typeof FriendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/my-money': typeof MyMoneyRoute
  '/settings': typeof SettingsRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/friends': typeof FriendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/my-money': typeof MyMoneyRoute
  '/settings': typeof SettingsRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/friends/': typeof FriendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/my-money'
    | '/settings'
    | '/friends/$friendId'
    | '/friends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/my-money'
    | '/settings'
    | '/friends/$friendId'
    | '/friends'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/my-money'
    | '/settings'
    | '/friends/$friendId'
    | '/friends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  MyMoneyRoute: typeof MyMoneyRoute
  SettingsRoute: typeof SettingsRoute
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
  FriendsIndexRoute: typeof FriendsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-money': {
      id: '/my-money'
      path: '/my-money'
      fullPath: '/my-money'
      preLoaderRoute: typeof MyMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/': {
      id: '/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$friendId': {
      id: '/friends/$friendId'
      path: '/friends/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  MyMoneyRoute: MyMoneyRoute,
  SettingsRoute: SettingsRoute,
  FriendsFriendIdRoute: FriendsFriendIdRoute,
  FriendsIndexRoute: FriendsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
